package main

import (
	"encoding/json"
	"net/http"

	"github.com/router-for-me/CLIProxyAPI/v7/sdk/pluginapi"
)

func managementRegister() ([]byte, error) {
	return okEnvelope(pluginapi.ManagementRegistrationResponse{Resources: []pluginapi.ResourceRoute{{Path: "/providers", Menu: "Universal Providers", Description: "Manage universal upstream providers."}}})
}

func managementHandle(raw []byte) ([]byte, error) {
	var req pluginapi.ManagementRequest
	if err := json.Unmarshal(raw, &req); err != nil {
		return nil, err
	}
	if req.Method != http.MethodGet || req.Path != "/providers" {
		return okEnvelope(pluginapi.ManagementResponse{StatusCode: http.StatusMethodNotAllowed, Headers: http.Header{"Allow": []string{http.MethodGet}}, Body: []byte("resource is read-only")})
	}
	return okEnvelope(pluginapi.ManagementResponse{StatusCode: http.StatusOK, Headers: http.Header{"Content-Type": []string{"text/html; charset=utf-8"}, "Content-Security-Policy": []string{"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'; base-uri 'none'; form-action 'none'"}}, Body: []byte(providersHTML)})
}

const providersHTML = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Universal Providers</title><style>
:root{color-scheme:dark;font-family:system-ui;background:#111827;color:#e5e7eb}body{max-width:1100px;margin:auto;padding:24px}button,input,select,textarea{font:inherit;border:1px solid #475569;border-radius:6px;padding:8px;background:#1e293b;color:inherit}button{cursor:pointer}.bar,.actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.card{border:1px solid #334155;border-radius:10px;padding:16px;margin:14px 0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}label{display:grid;gap:4px}textarea{min-height:90px}dialog{max-width:900px;width:90%;background:#111827;color:#e5e7eb;border:1px solid #475569;border-radius:10px}small{color:#94a3b8}.danger{color:#fecaca}#status{min-height:1.5em}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style></head><body>
<h1>Universal Providers</h1><p>This resource is not authenticated. Enter the CPA management key below; it is kept only in sessionStorage and sent as a Bearer token to the authenticated management API.</p>
<div class="bar"><label>Management key <input id="key" type="password" autocomplete="current-password"></label><button id="load">Load</button><button id="add">Add provider</button><button id="save">Save & hot reload</button></div><p id="status" role="status"></p><main id="list"></main>
<dialog id="editor"><form method="dialog"><h2 id="editor-title">Edit provider</h2><div class="grid"><label>ID<input name="id" required></label><label>Name<input name="name" required></label><label>Enabled<select name="enabled"><option value="true">Enable</option><option value="false">Disable</option></select></label><label>Protocol<select name="protocol"><option>openai</option><option>openai-response</option><option>claude</option><option>gemini</option></select></label><label>Base URL<input name="base-url" type="url" required></label><label>Reasoning effort<select name="reasoning-effort"><option>auto</option><option>none</option><option>minimal</option><option>low</option><option>medium</option><option>high</option><option>xhigh</option><option>max</option></select></label><label>Image generation<select name="image-generation"><option value="false">Disabled</option><option value="true">Enabled</option></select></label><label>Headers (one Name: Value per line)<textarea name="headers"></textarea></label><label>API keys<div id="keys"></div><button id="add-key" type="button">Add API key</button><small>Keys use password inputs and are never logged.</small></label><label>Models (name,alias,display,max-context,input modalities,output modalities)<textarea name="models"></textarea></label></div><p class="actions"><button value="cancel">Cancel</button><button id="apply" value="default">Apply</button></p></form></dialog>
<script>(()=>{'use strict';const endpoint='/v0/management/plugins/universal-provider/config',storeKey='universal-provider-management-key';let cfg={},providers=[],editing=-1;const $=id=>document.getElementById(id),status=m=>$('status').textContent=m;
const key=()=>$('key').value.trim();$('key').value=sessionStorage.getItem(storeKey)||'';$('key').addEventListener('change',()=>sessionStorage.setItem(storeKey,key()));
function el(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);return n}function lines(v){return String(v||'').split(/\n/).map(x=>x.trim()).filter(Boolean)}
function keyRow(entry={}){const row=el('div');row.className='actions';const secret=el('input'),weight=el('input'),remove=el('button','Remove');secret.type='password';secret.autocomplete='new-password';secret.placeholder='API key';secret.value=entry['api-key']||'';weight.type='number';weight.min='1';weight.max='1000000';weight.value=entry.weight||1;remove.type='button';remove.onclick=()=>row.remove();row.append(secret,weight,remove);return row}$('add-key').onclick=()=> $('keys').append(keyRow());
function render(){const root=$('list');root.replaceChildren();providers.forEach((p,i)=>{const c=el('section');c.className='card';const h=el('h2',p.name+' ('+p.id+')');c.append(h,el('p',(p.enabled?'Enabled':'Disabled')+' · '+p.protocol+' · '+p['base-url']));const a=el('div');a.className='actions';[['Edit',()=>open(i)],['Copy',()=>{const q=structuredClone(p);q.id=p.id+'-copy';q.name=p.name+' Copy';providers.splice(i+1,0,q);render()}],[p.enabled?'Disable':'Enable',()=>{p.enabled=!p.enabled;render()}],['Delete',()=>{if(confirm('Delete provider '+p.name+'? This cannot be undone after saving.')){providers.splice(i,1);render()}}]].forEach(([x,f])=>{const b=el('button',x);b.type='button';b.addEventListener('click',f);a.append(b)});c.append(a);root.append(c)})}
async function api(method,body){if(!key())throw Error('Management key is required');sessionStorage.setItem(storeKey,key());const r=await fetch(endpoint,{method,headers:{Authorization:'Bearer '+key(),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error('HTTP '+r.status+': '+await r.text());return r.status===204?{}:r.json()}
$('load').onclick=async()=>{try{cfg=await api('GET');if(Array.isArray(cfg.providers)){providers=structuredClone(cfg.providers)}else if(cfg.protocol||cfg['base-url']||Array.isArray(cfg.models)){providers=[{id:'legacy',name:'Legacy provider',enabled:true,protocol:cfg.protocol||'openai','base-url':cfg['base-url']||'',headers:cfg.headers||{},'api-key-entries':cfg['api-key-entries']||[],models:cfg.models||[],'image-generation':!!cfg['image-generation'],'reasoning-effort':cfg['reasoning-effort']||'auto'}]}else{providers=[]}render();status('Loaded '+providers.length+' providers')}catch(e){status(e.message)}};
$('save').onclick=async()=>{try{const next={...cfg,providers};if(Object.hasOwn(cfg,'enabled'))next.enabled=cfg.enabled;if(Object.hasOwn(cfg,'priority'))next.priority=cfg.priority;cfg=await api('PUT',next).then(()=>next);status('Saved. CPA will hot reload the plugin configuration.')}catch(e){status(e.message)}};
$('add').onclick=()=>open(-1);function open(i){editing=i;const p=i<0?{id:'',name:'',enabled:true,protocol:'openai','base-url':'','headers':{},'api-key-entries':[],'models':[],'image-generation':false,'reasoning-effort':'auto'}:providers[i];const f=$('editor').querySelector('form');$('editor-title').textContent=i<0?'Add provider':'Edit provider';for(const n of ['id','name','protocol','base-url','reasoning-effort'])f.elements[n].value=p[n]??'';for(const n of ['enabled','image-generation'])f.elements[n].value=String(!!p[n]);f.elements.headers.value=Object.entries(p.headers||{}).map(([k,v])=>k+': '+v).join('\n');$('keys').replaceChildren(...(p['api-key-entries']||[]).map(keyRow));if(!$('keys').children.length)$('keys').append(keyRow());f.elements.models.value=(p.models||[]).map(m=>[m.name,m.alias||'',m['display-name']||'',m['max-context-length']||0,(m['input-modalities']||[]).join('|'),(m['output-modalities']||[]).join('|')].join(',')).join('\n');$('editor').showModal()}
$('apply').onclick=e=>{e.preventDefault();const f=$('editor').querySelector('form'),g=n=>f.elements[n].value.trim(),headers={};lines(g('headers')).forEach(x=>{const i=x.indexOf(':');if(i>0)headers[x.slice(0,i).trim()]=x.slice(i+1).trim()});const p={id:g('id'),name:g('name'),enabled:g('enabled')==='true',protocol:g('protocol'),'base-url':g('base-url'),headers,'api-key-entries':[...$('keys').children].map(row=>({'api-key':row.children[0].value.trim(),weight:Number(row.children[1].value||1)})).filter(x=>x['api-key']),models:lines(g('models')).map(x=>{const [name,alias,display,max,input,output]=x.split(',');return {name:name.trim(),alias:(alias||'').trim(),'display-name':(display||'').trim(),'max-context-length':Number(max||0),'input-modalities':(input||'').split('|').filter(Boolean),'output-modalities':(output||'').split('|').filter(Boolean)}}),'image-generation':g('image-generation')==='true','reasoning-effort':g('reasoning-effort')};if(!p.id||!p.name||!p['base-url']){status('ID, name and base URL are required');return}if(editing<0)providers.push(p);else providers[editing]=p;$('editor').close();render()};
render()})()</script></body></html>`
